<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="2" name="pytest" skips="0" tests="8" time="0.407"><testcase classname="pytests.test_index" file="pytests/test_index.py" line="10" name="test_conda_environment_activated" time="0.0016655921936035156"></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="13" name="test_restaurant_name_func" time="0.0005517005920410156"></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="18" name="test_restaurant_rating_func" time="0.0005323886871337891"></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="23" name="test_is_better_func" time="0.0005257129669189453"></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="29" name="test_is_cheaper_func" time="0.0007865428924560547"></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="35" name="test_high_rating_func" time="0.0005309581756591797"></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="41" name="test_mean_review_count_func" time="0.002791881561279297"><failure message="AssertionError: assert 3.858333333333333 == 1261.0
 +  where 3.858333333333333 = mean_review_count([{&apos;categories&apos;: [{&apos;alias&apos;: &apos;seafood&apos;, &apos;title&apos;: &apos;Seafood&apos;}, {&apos;alias&apos;: &apos;gourmet&apos;, &apos;title&apos;: &apos;Gourmet&apos;}, {&apos;alias&apos;: &apos;Shellf...808088832532, &apos;longitude&apos;: -106.619402244687}, &apos;display_phone&apos;: &apos;(505) 266-0550&apos;, &apos;distance&apos;: 4033.6583235266075, ...}])">def test_mean_review_count_func():
        assert &apos;mean_review_count&apos; in ipynb.fs.full.index.__dict__, &quot;The mean_review_count function must be defined&quot;
&gt;       assert mean_review_count(restaurant_list) == 1261.0
E       AssertionError: assert 3.858333333333333 == 1261.0
E        +  where 3.858333333333333 = mean_review_count([{&apos;categories&apos;: [{&apos;alias&apos;: &apos;seafood&apos;, &apos;title&apos;: &apos;Seafood&apos;}, {&apos;alias&apos;: &apos;gourmet&apos;, &apos;title&apos;: &apos;Gourmet&apos;}, {&apos;alias&apos;: &apos;Shellf...808088832532, &apos;longitude&apos;: -106.619402244687}, &apos;display_phone&apos;: &apos;(505) 266-0550&apos;, &apos;distance&apos;: 4033.6583235266075, ...}])

pytests/test_index.py:44: AssertionError</failure></testcase><testcase classname="pytests.test_index" file="pytests/test_index.py" line="45" name="test_mediam_review_count_func" time="0.0012013912200927734"><failure message="AssertionError: assert 3.225 == 1284.5
 +  where 3.225 = median_review_count([{&apos;categories&apos;: [{&apos;alias&apos;: &apos;seafood&apos;, &apos;title&apos;: &apos;Seafood&apos;}, {&apos;alias&apos;: &apos;gourmet&apos;, &apos;title&apos;: &apos;Gourmet&apos;}, {&apos;alias&apos;: &apos;Shellf...808088832532, &apos;longitude&apos;: -106.619402244687}, &apos;display_phone&apos;: &apos;(505) 266-0550&apos;, &apos;distance&apos;: 4033.6583235266075, ...}])">def test_mediam_review_count_func():
        assert &apos;median_review_count&apos; in ipynb.fs.full.index.__dict__, &quot;The median_review_count function must be defined&quot;
&gt;       assert median_review_count(restaurant_list) == 1284.5
E       AssertionError: assert 3.225 == 1284.5
E        +  where 3.225 = median_review_count([{&apos;categories&apos;: [{&apos;alias&apos;: &apos;seafood&apos;, &apos;title&apos;: &apos;Seafood&apos;}, {&apos;alias&apos;: &apos;gourmet&apos;, &apos;title&apos;: &apos;Gourmet&apos;}, {&apos;alias&apos;: &apos;Shellf...808088832532, &apos;longitude&apos;: -106.619402244687}, &apos;display_phone&apos;: &apos;(505) 266-0550&apos;, &apos;distance&apos;: 4033.6583235266075, ...}])

pytests/test_index.py:48: AssertionError</failure></testcase></testsuite>